In [4]:
import os
import glob
import numpy as np
import pandas as pd
import seaborn as sns
from pathlib import Path
import matplotlib.pyplot as plt

from vip_slap2_analysis.glutamate import summary as gs
from vip_slap2_analysis.metadata.build_dataset_quality_overview import (
    build_dataset_quality_overview,
)

sns.set()
sns.set_style('white')
params = {'legend.fontsize': 'x-large',
         'axes.labelsize': 'xx-large',
         'axes.titlesize':'xx-large',
         'xtick.labelsize':'xx-large',
         'ytick.labelsize':'xx-large'}
plt.rcParams.update(params)

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

C:\Users\andrew.shelton\AppData\Local\Temp\ipykernel_8260\447993677.py:23: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [5]:
dataset_root = Path(r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics")
session_summary_path = dataset_root / "VIP_SD_summary.xlsx"

mouse_ids = [803496,804730,804733,810196,803121,809047,826033,834788,838410]  # replace with whichever mice you want

overview_df = build_dataset_quality_overview(
    dataset_root=dataset_root,
    session_summary_path=session_summary_path,
    mouse_ids=mouse_ids,
    include_expression_checks=False,
    paradigm_filter="change_detection_passive",
)

overview_df.head()

,mouse_id,session_id,session_date,session_number,indicator1,indicator2,session_type,stimulus,quality,quality_simple,flags,notes,session_dir
0,803121,803121_2025-10-29_11-19-29,2025-10-29,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
1,803121,803121_2025-10-30_11-13-32,2025-10-30,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
2,803121,803121_2025-10-31_13-05-26,2025-10-31,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
3,803121,803121_2025-11-01_19-00-21,2025-11-01,5,iGluSnFR4,RCaMP3,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
4,803121,803121_2025-11-05_11-16-57,2025-11-05,6,iGluSnFR4,RCaMP3,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...

In [6]:
overview_df

,mouse_id,session_id,session_date,session_number,indicator1,indicator2,session_type,stimulus,quality,quality_simple,flags,notes,session_dir
0,803121,803121_2025-10-29_11-19-29,2025-10-29,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
1,803121,803121_2025-10-30_11-13-32,2025-10-30,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
2,803121,803121_2025-10-31_13-05-26,2025-10-31,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
3,803121,803121_2025-11-01_19-00-21,2025-11-01,5,iGluSnFR4,RCaMP3,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
4,803121,803121_2025-11-05_11-16-57,2025-11-05,6,iGluSnFR4,RCaMP3,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
5,803121,803121_2025-11-06_12-12-23,2025-11-06,7,iGluSnFR4,RCaMP3,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
6,803496,803496_2025-07-25_13-02-10,2025-07-25,2,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
7,803496,803496_2025-07-28_08-04-39,2025-07-28,3,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
8,803496,803496_2025-07-29_13-34-35,2025-07-29,4,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
9,803496,803496_2025-07-30_10-05-23,2025-07-30,5,iGluSnFR4,,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
10,803496,803496_2025-07-31_09-43-28,2025-07-31,6,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
11,803496,803496_2025-08-01_13-22-49,2025-08-01,7,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
12,804730,804730_2025-07-25_14-08-35,2025-07-25,2,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
13,804730,804730_2025-07-28_13-57-34,2025-07-28,3,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
14,804730,804730_2025-07-29_14-55-04,2025-07-29,4,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
15,804730,804730_2025-07-30_11-11-11,2025-07-30,5,iGluSnFR4,,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
16,804730,804730_2025-07-31_11-45-27,2025-07-31,6,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
17,804730,804730_2025-08-01_14-22-38,2025-08-01,7,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
18,804733,804733_2025-07-25_15-17-00,2025-07-25,2,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
19,804733,804733_2025-07-28_19-00-06,2025-07-28,3,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
20,804733,804733_2025-07-29_16-02-24,2025-07-29,4,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
21,804733,804733_2025-07-30_12-59-44,2025-07-30,5,iGluSnFR4,,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
22,804733,804733_2025-07-31_13-29-01,2025-07-31,6,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
23,804733,804733_2025-08-01_15-20-32,2025-08-01,7,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
24,809047,809047_2025-10-29_10-16-32,2025-10-29,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
25,809047,809047_2025-10-30_10-06-43,2025-10-30,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
26,809047,809047_2025-10-31_12-00-50,2025-10-31,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
27,809047,809047_2025-11-01_17-51-59,2025-11-01,5,iGluSnFR4,RCaMP3,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
28,809047,809047_2025-11-05_10-13-00,2025-11-05,6,iGluSnFR4,RCaMP3,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
29,809047,809047_2025-11-06_11-05-31,2025-11-06,7,iGluSnFR4,RCaMP3,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
30,810196,810196_2025-07-25_16-24-20,2025-07-25,2,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
31,810196,810196_2025-07-28_19-59-05,2025-07-28,3,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
32,810196,810196_2025-07-29_17-02-41,2025-07-29,4,iGluSnFR4,,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
33,810196,810196_2025-07-31_08-28-08,2025-07-30,5,iGluSnFR4,,novel,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
34,810196,810196_2025-07-31_14-19-46,2025-07-31,6,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
35,810196,810196_2025-08-01_16-37-27,2025-08-01,7,iGluSnFR4,,novel+,images_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
36,826033,826033_2026-02-17_13-13-55,2026-02-17,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,stimlus ID not recorded properly,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
37,826033,826033_2026-02-18_11-57-04,2026-02-18,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
38,826033,826033_2026-02-19_13-47-57,2026-02-19,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
39,826033,826033_2026-02-21_09-23-34,2026-02-21,5,iGluSnFR4,RCaMP3,familiar,images_A,good,good,MoCo failed in last 3min of experiment,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
40,826033,826033_2026-02-23_10-45-21,2026-02-23,6,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
41,826033,826033_2026-02-24_14-14-45,2026-02-24,7,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,Some photodamage to a small segment of a large...,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
42,826033,826033_2026-02-25_08-49-29,2026-02-25,8,iGluSnFR4,RCaMP3,novel,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
43,826033,826033_2026-02-26_12-40-54,2026-02-26,9,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
44,826033,826033_2026-02-27_13-53-35,2026-02-27,10,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
45,834788,834788_2026-03-02_10-18-42,2026-03-02,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
46,834788,834788_2026-03-03_09-22-19,2026-03-03,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
47,834788,834788_2026-03-04_08-43-07,2026-03-04,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
48,834788,834788_2026-03-05_08-11-16,2026-03-05,5,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
49,834788,834788_2026-03-17_15-17-36,2026-03-17,6,iGluSnFR4,RCaMP3,novel,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
50,834788,834788_2026-03-19_09-05-56,2026-03-19,7,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
51,834788,834788_2026-03-20_12-44-00,2026-03-20,8,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
52,838410,838410_2026-03-02_12-40-55,2026-03-02,2,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
53,838410,838410_2026-03-03_13-49-07,2026-03-03,3,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
54,838410,838410_2026-03-04_12-54-47,2026-03-04,4,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
55,838410,838410_2026-03-05_10-16-37,2026-03-05,5,iGluSnFR4,RCaMP3,familiar,images_A,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
56,838410,838410_2026-03-20_10-00-59,2026-03-09,8,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
57,838410,838410_2026-03-18_16-43-23,2026-03-18,6,iGluSnFR4,RCaMP3,novel,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...
58,838410,838410_2026-03-19_13-06-48,2026-03-19,7,iGluSnFR4,RCaMP3,novel+,image_B,good,good,,,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...